# Render部署配置 - 修复Python版本兼容性问题
services:
  - type: web
    name: est-survival-web-app
    env: python
    plan: free
    # 指定Python版本为3.9以避免兼容性问题
    runtime: python-3.9.18
    buildCommand: |
      python -m pip install --upgrade pip==23.3.1
      pip install setuptools==68.2.2 wheel==0.41.2
      pip install -r requirements-minimal.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /